### ISSUE TITLE
Update orientation of GNSS module installation illustration in Wiki 

### ISSUE THREAD

**Issue by philltran** [rakstars/WisBlock-RAK4631-Helium-Mapper#1]
I suggest updating orientation of GNSS module installation illustration in Wiki. I helped someone troubleshoot their WisBlock mapper who installed the GNSS module backwards on the baseboard because they matched the orientation on the illustration. 

<img width="1246" alt="wisblock-mapper-tut-annotated" src="https://user-images.githubusercontent.com/812816/147670516-ea7e6b07-6a69-40df-a4df-d6f5178cb420.png">

Attached is my suggested edit. 

![wisblock-mapper-tut-01](https://user-images.githubusercontent.com/812816/147670309-9c1a2dbb-19d1-4979-b657-7097074db0a8.png)

Thanks for the great tutorial!

**Comment by johansmacias** [comment]
Nice finding. Thank you for your suggestion and comments! We've applied it on this wiki and the other sites where this tutorial is published.
