### ISSUE TITLE
Device locking up

### ISSUE THREAD

**Issue by T3chie-404** [rakstars/WisBlock-RAK4631-Helium-Mapper#4]
I'm on v1.0.2 and i find myself having to press the reset button to get it to send packets. I'll leave on a trip and a few updates go out, but after a few minutes between hotspots and it's like it goes to sleep never to wake again until i press the reset.

As a drive I'll watch the debug packets come into console, then go through a dead zone, and when i get near another hotspot it doesn't ever send a packet. 

Also watching cargo.helium.com I'll see the tracking stop at the same point that i went out of coverage of a hotspot and it won't pick back up when i get to the coverage of another hotspot.

Any suggestions to try?

**Comment by johansmacias** [comment]
Suggestions for the scenario described might not apply at this moment.
