### ISSUE TITLE
Is this rep[o still maintained?

### ISSUE THREAD

**Issue by beegee-tokyo** [rakstars/WisBlock-RAK4631-Helium-Mapper#7]
@johansmacias

Long time no updates, no issues answered, pull-request not reviewed.

If this repo is no longer maintained here, I propose to move it to RAKwireless Github account and maintain it there.

**Comment by johansmacias** [comment]
@beegee-tokyo

I agree with your recommendation of moving it there. Surely it will make it easier for you at RAK to maintain it there.
